# Tomcat Server
server:
  port: 8080

# Logging
logging:
  level:
    root: INFO



# Spring Boot
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: edu
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html
  web:
    resources:
      static-locations: file:src/main/resources/static/
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-request-size: 20MB
      enabled: true
      max-file-size: 20MB
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 1.0
          max-tokens: 1000
springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: none
    tags-sorter: none
  group-configs:
    - group: Chapter_1_Chat_Completion_Controller
      paths-to-match: /ch1/**
    - group: Chapter_2_Prompt_Template_Controller
      paths-to-match: /ch2/**
